### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by nandish1409** [thisisashukla/twitter-anuvaad#1] opened 2022-12-18 03:18 UTC
im giving the same input(your tweet) .. https://colab.research.google.com/drive/1U9ZRWfry6O3UXtZPArxLzlbFx6XWQiOI?usp=sharing (collab link) can you pls check.
its converting an english statement to other languages without error but if i give an hindi statement written english like (mai twitter ke lie ek anuvaadak bana raha hu) its throwing an error(JSONDecodeError: Expecting value: line 1 column 1 (char 0))
![image](https://user-images.githubusercontent.com/96170109/208279689-0d8d06de-2215-42e6-a873-cb253334538a.png)

**Comment by thisisashukla** [comment] 2022-12-20 17:36
Thanks for creating the issue @nandish1409. This is being caused by an API the colab code uses to translate the text. That API is in a suspended state resulting in 410 response code. 

API Link: https://huggingface.co/spaces/Harveenchadha/oiTrans

I am closing this issue since i can not resolve it at this point of time.

**Closed as completed by thisisashukla** 2022-12-20 17:36 UTC
